version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=testpasswd
      - MYSQL_DATABASE=codeSherpas
    ports:
      - "3306:3306"
    volumes:
      - "./dbinit:/docker-entrypoint-initdb.d"

#mysql -h 127.0.0.1 -u root -ptestpasswd -P 3306 codeSherpas
