CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    surname VARCHAR(64) NOT NULL,
    email VARCHAR(255) NOT NULL,
    birthdate DATE NOT NULL
);